#!/usr/bin/env python

import rospy
import actionlib
import time
from lingua_tests.msg import SetBrakesResult, SetBrakesAction
from lingua_tests.srv import GetBrakeStatus

brakes_locked = True

def get_status(req):
  return brakes_locked

def callback(goal):
  global brakes_locked
  brakes_locked = goal.enabled
  server.set_succeeded(result=SetBrakesResult(True))

if __name__ == '__main__':
  rospy.init_node("brakes")

  rospy.Service('/brakes/locked', GetBrakeStatus, get_status)
  
  server = actionlib.SimpleActionServer('brakes', SetBrakesAction, execute_cb=callback, auto_start=False)
  server.start()
  print('Ready')
  rospy.spin()