#!/usr/bin/env python
import rospy
import json

from wire_msgs.msg import WorldState

world_state = None

def get_objects(search):
  search = json.loads(search)
  found = []
  
  for obj in world_state.objects:
    matches = []

    for prop in obj.properties:
      prop_id = prop.attribute
      if prop_id in search and search[prop_id] in prop.pdf.values:
        matches.append(prop_id)
    
    if len(set(search.keys()).difference(matches)) == 0:
      found.append(obj.ID)

  return found

# def get_object_position(object_id):
#   for 
  
def state_cb(msg):
  global world_state
  world_state = msg

rospy.init_node('KB')

rospy.Subscriber('/world_state', WorldState, state_cb)

rospy.sleep(1)

print(get_objects(json.dumps({'class_label': 'ball', 'color': 'red'})))

# rospy.spin()