#!/usr/bin/env python

import rospy
import actionlib
import time
from rv_msgs.msg import ActuateGripperAction, ActuateGripperResult, ActuateGripperFeedback
from rv_msgs.msg import MoveToPoseAction, MoveToPoseResult

from sensor_msgs.msg import JointState

delta = 0.037

def callback1(goal):
  global delta
  for n in range(1):
    print('Open gripper:',n)
    rospy.sleep(1)
    server1.publish_feedback(ActuateGripperFeedback(feedback=1))
  delta = goal.width
  server1.set_succeeded(ActuateGripperResult(result=1))

def callback2(goal):
  print(goal)
  for n in range(3):
    print('Move to pose:',n)
    rospy.sleep(1)
  server2.set_succeeded(MoveToPoseResult(result=1))

if __name__ == '__main__':
  rospy.init_node("manipulator")
  server1 = actionlib.SimpleActionServer('/arm/gripper', ActuateGripperAction, execute_cb=callback1, auto_start=False)
  server2 = actionlib.SimpleActionServer('/arm/cartesian/pose', MoveToPoseAction, execute_cb=callback2, auto_start=False)
  server1.start()
  server2.start()

  publisher = rospy.Publisher('/franka_gripper/joint_states', JointState, queue_size=1)
  print('Ready')

  while not rospy.is_shutdown():
    publisher.publish(JointState(position=[delta, delta]))
    rospy.sleep(0.5)