#!/usr/bin/env python

import rospy
import rospkg
import os
from openccg_ros.srv import Parse, ParseRequest
import xml.etree.ElementTree as ET

rospy.init_node('veil500')

rospack = rospkg.RosPack()
path = rospack.get_path('lingua_tests')

with open(os.path.join(path, 'data', 'Dataset/VEIL500', 'unlabelled_data_Feb-18-2015.xml')) as f:
  data = f.read()

tree = ET.fromstring(data)
tests = []

for idx, node in enumerate(tree.iter(tag='span')):
  if node.tag == 'span' and node.text.startswith('Old text : '):
    tests.append('. '.join(node.text.replace('Old text : ', '').split('\n')))

print(len(tests))

parser = rospy.ServiceProxy('/ccg/parse', Parse)

for test in tests:
  for sent in test.split('.'):
    print(parser(ParseRequest(text=sent)))
  break


